### ISSUE TITLE
pip.installed error on ubuntu container

### ISSUE THREAD

**Issue by noelmcloughlin** [noelmcloughlin/opensds-installer#2]
```
root@gke-kube1-default-pool-00fc1b96-1njp:/root# salt --versions-report      
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.13.0-1011-gcp
         system: Ubuntu 16.04 xenial
```
```
----------
          ID: tox
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 592, in installed
                  out = _check_pkg_version_format(pkg)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 176, in _check_pkg_version_format
                  ret['prefix'] = install_req.req.project_name
              AttributeError: 'Requirement' object has no attribute 'project_name'
     Started: 19:34:43.419590
    Duration: 24.418 ms
     Changes:   
----------
          ID: click
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 592, in installed
                  out = _check_pkg_version_format(pkg)
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 176, in _check_pkg_version_format
                  ret['prefix'] = install_req.req.project_name
              AttributeError: 'Requirement' object has no attribute 'project_name'
     Started: 19:34:43.447357
    Duration: 20.703 ms
     Changes:   
```
Install using pip worked.
```
root@gke-kube1-default-pool-00fc1b96-1njp:/root# exit
exit
bob@gke-kube1-default-pool-00fc1b96-1njp:~$ pip install tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/e6/41/4dcfd713282bf3213b0384320fa8841e4db032ddcb80bc08a540159d42a8/tox-3.0.0-py2.py3-none-any.whl (60kB)
    100% |################################| 61kB 4.8MB/s 
Collecting pluggy<1.0,>=0.3.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/82/05/43e3947125a2137cba4746135c75934ceed1863f27e050fc560052104a71/pluggy-0.6.0-py2-none-any.whl
Collecting six (from tox)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox)
  Downloading https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl (1.9MB)
    100% |################################| 1.9MB 678kB/s 
Collecting py>=1.4.17 (from tox)
  Downloading https://files.pythonhosted.org/packages/67/a5/f77982214dd4c8fd104b066f249adea2c49e25e8703d284382eb5e9ab35a/py-1.5.3-py2.py3-none-any.whl (84kB)
    100% |################################| 92kB 10.7MB/s 
Installing collected packages: pluggy, six, virtualenv, py, tox
Successfully installed pluggy py six-1.10.0 tox virtualenv
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bob@gke-kube1-default-pool-00fc1b96-1njp:~$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
bob@gke-kube1-default-pool-00fc1b96-1njp:~$ pytthon --version
-bash: pytthon: command not found
bob@gke-kube1-default-pool-00fc1b96-1njp:~$ python --version
Python 2.7.12
```
The error was generated by packages-formula.
```
packages:
  #see https://github.com/saltstack-formulas/packages-formula/blob/master/pillar.example
  pips:
    wanted:
      - tox
      - click
  pkgs:
    unwanted:
      - unattended-upgrades
    wanted:
      - python-setuptools
      - salt-api
      - git
      - make
          {% if grains.os_family == 'Debian' %}
      - python-pip
          {% elif grains.os_family == 'RedHat' %}
      - python2-pip
      - python-click
      - python-tox
          {% elif grains.os_family == 'Suse' %}
      - python-pip
          {% elif grains.os_family == 'Arch' %}
      - python2-pip
          {% endif %}
```
